<div class="container-fluid h-100">
	<div class="row h-100">
		<div class="col-md-1 banner">
			<div class="row h-100 justify-content-center align-items-start">
				<ul>
				<label for="">Vendas</label>
					<li>
						<a href="/cadastrar_venda">Cadastrar</a>
					</li>
					<li>
						<a href="/listar_vendas">Listar</a>
					</li>
					<br>
					<label for="">Produtos</label>
					<li>
						<a href="/cadastrar_prod">Cadastrar</a>
					</li>
					<li>
						<a href="/listar_produtos">Listar</a>
					</li>
					<br>
						<label for="">Clientes</label>
					<li>
						<a href="/inscreverse">Cadastrar</a>
					</li>
					<li>
						<a href="/listar_clientes">Listar</a>
					</li>
				</ul>
			</div>
		</div>

		<div class="col-md-11 pt-4 pl-5 pr-5">
			
			
		</div>
  </div>
</div>