<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar Clientes</title>
</head>
<body>
    <div class="container">
      <div class="box">
          <div class="box box-primary">
          <h3>Dados</h3>
          </div>
      </div>
   
        <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-bordered">
                    <thead>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>E-mail</th>
                        <th>Data Nascimento</th>
                    </thead>
                    <tbody>
                <?php
                
                    foreach ($this->view->clientes as $id => $cliente)
                    {
                    ?>
                        <tr>
                            <td><?php echo $id; ?></td>
                            <td><?php echo $cliente['nome']; ?></td>
                            <td><?php echo $cliente['cpf']; ?></td>
                            <td><?php echo $cliente['email']; ?></td>
                            <td><?php echo $cliente['data_nascimento']; ?></td>
                        </tr>
                    
                    <?php

                    }

                    
                ?>
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    
   
</body>
</html>