<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar Produtos</title>
    
</head>
<body>
    <div class="container">
      <div class="box">
          <div class="box box-primary">
          <h3>Dados</h3>
          </div>
      </div>
   
        <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-bordered">
                    <thead>
                        <th style=" text-align: center;width:10px;">ID</th>
                        <th style=" text-align: center;width:15px;">DESCRIÇÃO</th>
                        <th style=" text-align: center;width:15px;">VALOR UN.</th>
                    </thead>
                    <tbody>
                <?php
                
                    foreach ($this->view->produtos as $id => $produto)
                    {
                    ?>
                        <tr>
                            <td style=" text-align: center;"><?php echo $id; ?></td>
                            <td style=" text-align: left;"><?php echo utf8_decode($produto['descricao']); ?></td>
                            <td  style=" text-align: right;"> R$ <?php echo number_format($produto['preco'],2,",","."); ?></td>
                        </tr>
                    
                    <?php

                    }

                    
                ?>
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    
   
</body>
</html>